### ISSUE TITLE
Race Mulit lanauge idea

### ISSUE THREAD

**Issue by DiNaSoR** [DiNaSoR/WoWAR#4]
I am thinking of this to make it work with all versions what do you think? do we need to do that or keep each version separated?

```lua
-- Your base table in English
local p_race_en = {
    ["Blood Elf"] = { M1="Blood Elf", D1="Blood Elf", C1="Blood Elf", B1="Blood Elf", N1="Blood Elf", K1="Blood Elf", W1="Blood Elf", M2="Blood Elf", D2="Blood Elf", C2="Blood Elf", B2="Blood Elf", N2="Blood Elf", K2="Blood Elf", W2="Blood Elf" },
    -- Add other races here...
}

-- Your translated table in Arabic
local p_race_ar = {
    ["بلود إيلف"] = { M1="Blood Elf", D1="Blood Elf", C1="Blood Elf", B1="Blood Elf", N1="Blood Elf", K1="Blood Elf", W1="Blood Elf", M2="Blood Elf", D2="Blood Elf", C2="Blood Elf", B2="Blood Elf", N2="Blood Elf", K2="Blood Elf", W2="Blood Elf" },
    -- Add translations for other races here...
}

-- Function to dynamically select the table based on the current language
local function getP_Race(lang)
    if lang == 'AR' then
        return p_race_ar -- Return the Arabic table if the language is Arabic
    else
        return p_race_en -- Otherwise, return the English table
    end
end

-- Example usage
local currentLanguage = 'AR' -- Assuming you get this from WoWTR_Localization.lang or similar
local p_race = getP_Race(currentLanguage)

-- Accessing a value from p_race will now return the correct version based on the current language
-- For example, to access "Blood Elf" data in Arabic:
-- local raceData = p_race["بلود إيلف"] if currentLanguage == 'AR' else p_race["Blood Elf"]
```

**Comment by Platine-WOW** [comment]
It doesn't work that way.
A table is created to translate the name of the player's race in various noun cases.

["Human"] = { M1="Człowiek", D1="człowieka", C1="człowiekowi", B1="człowieka", N1="człowiekiem", K1="człowieku", W1="Człowieku", M2="Człowiek", D2="człowieka", C2="człowiekowi", B2="człowieka", N2="człowiekiem", K2="człowieku", W2="Człowieku" },

At the beginning there is the name in English that appears in the game.
Then, translations are entered in the individual elements of the table.
M1 is a nominative masculine translation, D1 is a masculine genitive translation, C2 is a feminine dative translation, D2 is a feminine accusative translation. If the code YOUR_RACE4 appears in the translation, the translation will be downloaded in the accusative case for the male (D1) or female (D2) form, depending on the player's gender.
We have such cases in Polish and in order for the translation text to be linguistically correct, such a table is needed.
